FROM docker.io/library/python:3.8-slim as build-stage

WORKDIR /app
COPY src /app/src
COPY requirements.txt /app/requirements.txt

RUN python setup.py bdist_wheel
RUN pip install

RUN pip install -r requirements.txt

FROM build-stage as test-stage

RUN python3 -m pytest --cov=pathfinders tests

COPY requirements-test.txt /app/requirements-test.txt

RUN pip install -r requirements-test.txt
RUN python3 -m pytest --cov=src tests
# TODO implement quality gates based on coverage
